<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,height=device-height,inital-scale=1.0,maximum-scale=1.0,user-scalable=no;">
    <title>关于<?php echo $this->payload->getAppName(); ?></title>
</head>
<body style="padding: 0 1rem;">
<?php if (!empty($this->payload->getLogo())): ?>
    <p><img style="width: 30%; display: block; margin: 0 auto;" src="<?php echo $this->payload->getLogo(); ?>"></p>
<?php endif; ?>
<?php echo $this->payload->getContent(); ?>
</body>
</html>